### ISSUE TITLE
Very useful, was reinventing this. How about nesteds?

### ISSUE THREAD

**Issue by vans163** [massemanet/velocity#1]
For example if you have  

```
[ 
  [ {id,1},{tagref,5},{queue, cant_flatten},{extra, [{index,77},{queue, 44}]} ], 
  [ {id,2},{tagref,7},{extra, [{index, 99},{queue, 0}]} ]
],
```

Is there a sane way to add that support, I see internally its using ETS, I am not sure if ETS can do query like that.

We want find(user, [extra], queue, 44)

**Comment by massemanet** [comment]
you mean something along the lines of this?

find(Table,[{extra,[{queue,44}]}]).

Sadly, I don't think there is a way to do that without scanning the whole Table.
Unless I misunderstand you, the workaround in this case would be to index {extra_queue,44} or some such.

**Comment by vans163** [comment]
Yea that is a way, I think the erlang way is just make more ets tables and try avoid nesting as much as possible (flatten if possible); as that is the work of object oriented programming and OOP is the devil.

Decode the JSON into a proplist.
Seperate the extra into a seperate ETS table or value.
Ofcourse keep a reference to id somwhere there somehow.

```
find(Table, queue, cant_flatten)
find(TableExtra, queue, 44) 
```
